openapi: 3.0.0
info: 
  title: sample API
  description: these is the description of the api 
  version: "1"

servers:
  - url: http://localhost:3001
    description: local development

tags:
  - name: common
paths:
  /health-check:
    get:
      tags:
        - common
      responses:
        200:
          description: everything is good
        500:
          description: something bad happen
          
